#!/usr/bin/env python3

from dlinked_list import DoublyLinkedList

if __name__ == '__main__':
    dlist = DoublyLinkedList()
    dlist.add_node_end(0)
    dlist.add_node_end(1)
    dlist.add_node_end(2)
    dlist.add_node_end(3)
    dlist.add_node_end(4)
    dlist.add_node_end(98)
    dlist.add_node_end(402)
    dlist.add_node_end(1024)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(5)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()
    print('-----------------------------------')
    dlist.delete_node_at_index(0)
    dlist.print_dlist()

