#!/usr/bin/env python3
from linked_list import LinkedListNum
from node import NodeNum

if __name__ == '__main__':
    my_list = LinkedListNum()
    my_list.add_node_end(0)
    my_list.add_node_end(1)
    my_list.add_node_end(2)
    my_list.add_node_end(3)
    my_list.add_node_end(4)
    my_list.add_node_end(98)
    my_list.add_node_end(402)
    my_list.add_node_end(1024)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(5)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()
    print('-----------------------------------')
    my_list.delete_node_at_index(0)
    my_list.print_list()

    # print(f'-> {len(my_list)} elements')
    # my_list.print_list()
    # n = my_list.pop_head_node()
    # print(f'- {n}')
    # print(f'-> {len(my_list)} elements')
    # my_list.print_list()
    # n = my_list.pop_head_node()
    # print(f'- {n}')
    # print(f'-> {len(my_list)} elements')
    # my_list.print_list()
    # my_list.free_list()
    # n = my_list.pop_head_node()
    # print(f'- {n}')
    # print(f'-> {len(my_list)} elements')